### ISSUE TITLE
PEP8 and PEP8 webhook for B-Tax

### ISSUE THREAD

**Issue by PeterDSteinberg** [PSLmodels/Cost-of-Capital-Calculator#144]
After merge of #143 , I'll do a review through all of B-Tax for style issues ([PEP8](https://www.python.org/dev/peps/pep-0008/).  Then add information to .travis.yml to make sure the PEP8 check is run on each PR push.

**Comment by jdebacker** [comment]
Checklist of scripts that have been updated to conform w/ PEP8 (with small exceptions for clarity):

- [x] `run_btax.py`
- [x] `calc_z.py`
- [ ] `calc_final_outputs.py`
- [x] `parameters.py`
- [ ] `read_bea.py`
...

**Comment by jdebacker** [comment]
Style checks were implemented with PR #263
