### ISSUE TITLE
Review dataframe operations to see where inplace=True may be used

### ISSUE THREAD

**Issue by PeterDSteinberg** [PSLmodels/Cost-of-Capital-Calculator#148]
* [ ] Review usages of dataframes in B-Tax and replace copy operations with in place operations where possible (reduce memory footprint, sometimes reduce CPU usage)
 * [ ] Make issues to do this dataframe in place usage check in OG-USA and Tax-Calculator

**Comment by PeterDSteinberg** [comment]
I noticed this when working on PEP8 issues as part of #146

**Comment by jdebacker** [comment]
These have been updated with PR #237.
