### ISSUE TITLE
Restructuring to avoid hard-coding parameters

### ISSUE THREAD

**Issue by codykallen** [PSLmodels/Cost-of-Capital-Calculator#181]
I don't like that E_c and E_nc are unaffected by changes in the interest rate `i`. I think parameters.py and btax_defaults.json could use serious reorganization, to move the many hard-coded parameters in parameters.py to user-controllable parameters. 

This would have a number of uses. For example, interest rates are predicted to rise in the coming years. Thus a user should be allowed to move i, E_c and E_nc together, but currently they can only change i.

**Comment by jdebacker** [comment]
Note that any changes to address this issue should also help with Issue #177.  This would more parameter should be easily defined in an input JSON file, but also that the reform run should get some of the values from the baseline run.

**Comment by jdebacker** [comment]
As of PR #230, CCC uses a parameters class the allows users to adjust all model parameter.
