### ISSUE TITLE
Parameter and variable name consistency

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Cost-of-Capital-Calculator#239]
Variables and parameters should be more consistent in naming conventions.  e.g.,
* for pass-through businesses, the suffixes `nc` of `PT` are both used.  It would be best to stick with `pt` throughout.
* for corporate businesses, the suffixes `c` and `corp` are both used.  It would be best to stick with `c` throughout.

**Comment by duncanhobbs** [comment]
I have worked on updating the variable and parameter names `nc` to `pt` and `corp` to `c`.

Would you like me to submit a PR to the master branch or to a development branch since this would break backward compatibility?

**Comment by jdebacker** [comment]
Resolved via PR #360
