### ISSUE TITLE
Update bokeh plot outputs in comp_output function

### ISSUE THREAD

**Issue by jdebacker** [PSLmodels/Cost-of-Capital-Calculator#287]
Need to use `json_item` instead of `components` in the passing of the bokeh plot items for output on Compute Studio, per [this issue](https://github.com/compute-tooling/compute-studio-kit/issues/7).

**Comment by hdoupe** [comment]
Thanks @jdebacker. I'll ping you when C/S is ready to do the swap to the new function. This should be sometime next week.

**Comment by jdebacker** [comment]
This was addressed with PR #289.
