### ISSUE TITLE
R&D Amortization

### ISSUE THREAD

**Issue by kpomerleau** [PSLmodels/Cost-of-Capital-Calculator#300]
Context: I am trying to estimate baseline METRs in a way that is consistent with CBO. One place that CCC breaks from CBO methodology is treatment of IP. CBO applies 5-year amortizations to R&D expenses starting in 2022. IT appears that CCC does not have this feature yet.

What would be the most straightforward way to apply 5-year amortization to intellectual property products, consistent with the TCJA?

Currently, it looks like IP is categorized as a general 5-year asset. As such, any change one makes to IP also impacts all other 5-year assets and vice-versa.

Would this be done at the asset level? Or is there a work around that allows one to apply special depreciation regimes to specific assets?

Any suggestions would be most welcome!

**Comment by jdebacker** [comment]
@kpomerleau Thanks for opening this issue.  Allowing one to change depreciation rules for specific asset types is something that is not easily done with CCC right now.  I would be great to add this feature and I can help if you have ideas.  Just not sure of the best way to balance having too many parameters to set and having more flexibility, but I'm sure there's a way.

A quick fix to change depreciation rules for a specific asset type is to adjust the rules in [`tax_depreciation_rates.csv`](https://github.com/PSLmodels/Cost-of-Capital-Calculator/blob/master/data/depreciation_rates/tax_depreciation_rates.csv).  I think what you'd want to do is to:
1) Edit the csv file to change the depreciation rules for the IP assets you want changed (with amortization you'd want to set the method to straight line then you can set the years to whatever the amortization period is that you want).
2) Then you'd execute `Cost-of-Capital-Calculator/data/create_asset_data.py` to create a new `ccc_asset_data.csv` file (maybe renaming it or keeping it in a separate directory).
3) Finally, when you want to run the model with these different depreciation/amortization rates, you'd create your asset class and point it to the new csv file.  e.g. `assets_reform = Assets(data='new_ccc_asset_data.csv')`

Let me know how that works for you in the short term and if you have suggestions on how best to add flexibility so users can change these parameters without creating a new asset dataset.  I think ideally one could change the depreciable life and method separately for each asset or for groups of assets together.

**Comment by kpomerleau** [comment]
Hey @jdebacker,

Thank you for the suggestion. I also came up with a potential solution that doesn't require making a new asset csv.

The current asset file indicates whether certain IP is expensed in the column 'Method'. Luck would have it that it corresponds to the IP that would be subject to 5-year SL amortization starting in 2022. Other IP, such as movie productions, which use 15-year econ depreciation, would continue to qualify for bonus until that expires.

What I did:

1. Created a new parameter called ip_amortization, which can either be set to True or False.
2. Add code to the 'npv_tax_depr' function in calcfunctions.py to calculate 5-year SL if an asset is IP, currently using the expensing method, and if ip_amortization == true

I am happy to share code if you think this may help get to a long-term solution.

**Comment by jdebacker** [comment]
@kpomerleau Absolutely - if you want to open a PR with changes for me to review, I'd be happy to do so.  Thanks!

**Comment by jdebacker** [comment]
@kpomerleau PR #306 now allows changes to depreciation life and system by asset type.  If you are interested using this and the can't follow examples from that PR conversation or the new tests in `tests/test_parameters.py`, I'll be glad to help you out.
