### ISSUE TITLE
2030 projections?

### ISSUE THREAD

**Issue by kpomerleau** [PSLmodels/Cost-of-Capital-Calculator#303]
Hi Jason,

How difficult would it be to update the model to project to 2030?

Thanks,

Kyle

**Comment by jdebacker** [comment]
@kpomerleau Business tax parameters can be updated easily.  But I'm not aware of Tax-Calculator being able to go out to 2030.  

@MattHJensen What year can we use TC out to?  I see growth rates only until 2029...

**Comment by MattHJensen** [comment]
> What year can we use TC out to? I see growth rates only until 2029...

We are expecting to update to 2030 next week.

**Comment by jdebacker** [comment]
@MattHJensen thanks for the quick follow up.  

I'll get a PR open to update CCC on about the same time frame.

**Comment by MattHJensen** [comment]
We just released taxcalc 2.9.0. Please let me know if anything doesn't go smoothly.

**Comment by jdebacker** [comment]
Issue resolved with PR #304
