### ISSUE TITLE
GH Docs URL on CCC Home page not working

### ISSUE THREAD

**Issue by hdoupe** [PSLmodels/Cost-of-Capital-Calculator#322]
This morning I noticed that this link does not work:

http://pslmodels.github.io/cost-of-capital-calculator

but this one does:

http://pslmodels.github.io/Cost-of-Capital-Calculator

The former link is what is listed on the CCC repo home page:

![Screenshot from 2020-10-03 12-04-46](https://user-images.githubusercontent.com/9206065/94996123-ace38500-0570-11eb-9d37-fb823afeabe9.png)

It seems like GH Pages URLs are now case sensitive?

**Comment by jdebacker** [comment]
Just fixed that - thanks for noticing @hdoupe.

Surprising these are case sensitive - and they display in all lower case.
